### PR TITLE
Tgc

### PR DESCRIPTION
**Pull request by chasakara**

### CODE REVIEW

**Review by Niki-Tester — CHANGES_REQUESTED** [review]
SECRET_KEY needs to be changed back to DJANGO_SECRET_KEY, as this is how it is defined on the server.
This is because we will have other secret keys defined later when we implement the APIs

**Review by chasakara — COMMENTED** [review]
views and urls added

**Review by Niki-Tester — CHANGES_REQUESTED** [review]
We are not using boot-strap in this project, we are instead using https://bulma.io/
I've requested a change, would you mind just going through and removing all boot-strap related classes and imports.
We can then add the bulma cdn in the base.html file, and use the bulma classes. But we can do that separately

**Review by Niki-Tester — APPROVED** [review]
I will merge these changes and make the changes :)

**Pull request merged**
